### ISSUE TITLE
Mostrando numero desconectado, mesmo estando conectado index.php?class=ListDispositivosController

### ISSUE THREAD

**Issue by willph** [aspiretony/MDcWPPManagementPHP#1]
Em LISTAR E OU CONECTAR DISPOSITIVO, mostra um dispositivo que acabei de conectar, porem na lista mostra ele desconectado.

![image](https://user-images.githubusercontent.com/17226802/167657511-7ab4a329-252a-4a51-8563-4460f49f44d5.png)

Não conseguir localizar os arquivos que fazem a ponte entre o controller e o wppconnect

**Comment by aspiretony** [comment]
Olá, está versão está descontinuada, fiz uma nova versão com praticamente todos os bugs sanados e sem erros de conexão. Estou só configurando o composer e irei subir ela, sobre os arquivos que fazem a ponte pode olhar em /app/control/sessoeseclientes/ caso ainda queira utilizar esta versão.
